BBGymManagement/Controllers/CategoryController.cs
using BBGymManagement.Models.Entities;
using BBGymManagement.MVVM;
using BBGymManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBGymManagement.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        private ProductService _productService=new ProductService();

        public ActionResult GymMembership()
        {
            var products = _productService.Get(x => x.CategoryId == Models.Entities.CategoryId.GymMembership);
            var model = new List<ProductViewModel>();
            foreach (var item in products)
            {
                model.Add(new ProductViewModel { Id=item.Id, Name=item.Name,Price=item.Price,ImageUrl=item.ImageUrl});
            }
            return View(model);  
        }

        public ActionResult PersonalTrainer()
        {
            var products = _productService.Get(x => x.CategoryId == Models.Entities.CategoryId.PersonalTrainer);
            var model = new List<ProductViewModel>();
            foreach (var item in products)
            {
                model.Add(new ProductViewModel {Id=item.Id, Name = item.Name, Price = item.Price, ImageUrl = item.ImageUrl });
            }
            return View(model);
        }
    }
}

BBGymManagement/Controllers/LoginController.cs
using BBGymManagement.Models.Entities;
using BBGymManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Security.Principal;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BBGymManagement.Controllers
{
    public class LoginController : Controller
    {
        CustomerService _customerService = new CustomerService();
        RolService _rolService = new RolService();

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Obsolete]
        public ActionResult Index(string email, string password)
        {

            if (_customerService.IsAdmin(email, password))
            {
                var user = _customerService.Get(x => x.Email == email).FirstOrDefault();
                var role = _rolService.GetById(user.RolId).Name;
                var now = DateTime.UtcNow.ToLocalTime();
                string userData = email + ";" + role;
                var ticket = new FormsAuthenticationTicket(1, email, now, now.Add(FormsAuthentication.Timeout), true, userData, FormsAuthentication.FormsCookiePath);
                var encryptedTicket = FormsAuthentication.Encrypt(ticket);

                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                cookie.HttpOnly = true;
                if (ticket.IsPersistent)
                {
                    cookie.Expires = ticket.Expiration;
                }
                cookie.Secure = FormsAuthentication.RequireSSL;
                cookie.Path = FormsAuthentication.FormsCookiePath;
                if (FormsAuthentication.CookieDomain != null)
                {
                    cookie.Domain = FormsAuthentication.CookieDomain;
                }

                string encrypetedTicket = FormsAuthentication.Encrypt(ticket);
                FormsAuthentication.SetAuthCookie(encrypetedTicket, false);
                
                return Redirect("~/Admin/Home/Index");
            }
            else if (_customerService.IsCustomer(email, password))
            {
                var user = _customerService.Get(x => x.Email == email).FirstOrDefault();
                var role = _rolService.GetById(user.RolId).Name;
                string userData = email + ";" + role;
                var now = DateTime.UtcNow.ToLocalTime();
                var ticket = new FormsAuthenticationTicket(1, email, now, now.Add(FormsAuthentication.Timeout), true, userData, FormsAuthentication.FormsCookiePath);
                var encryptedTicket = FormsAuthentication.Encrypt(ticket);

                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                cookie.HttpOnly = true;
                if (ticket.IsPersistent)
                {
                    cookie.Expires = ticket.Expiration;
                }
                cookie.Secure = FormsAuthentication.RequireSSL;
                cookie.Path = FormsAuthentication.FormsCookiePath;
                if (FormsAuthentication.CookieDomain != null)
                {
                    cookie.Domain = FormsAuthentication.CookieDomain;
                }

                string encrypetedTicket = FormsAuthentication.Encrypt(ticket);
                FormsAuthentication.SetAuthCookie(encrypetedTicket, false);

                return Redirect("~/Home/Index");
            }
            else
            {
                TempData["LoginError"] = "Email or password is wrong";
                return View();
            }

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

BBGymManagement/Controllers/RegisterController.cs
using BBGymManagement.Models.Entities;
using BBGymManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using BBGymManagement.Helpers;
namespace BBGymManagement.Controllers
{
    public class RegisterController : Controller
    {
        CustomerService _customerService = new CustomerService();
        RolService _rolService = new RolService();



        public bool IsValidatiıon(Customer model)
        {
            var validation = true;

            if (string.IsNullOrEmpty(model.Name?.Trim()))
            {
                validation = false;
            }
            if (string.IsNullOrEmpty(model.Surname?.Trim()))
            {
                validation = false;
            }
            if (string.IsNullOrEmpty(model.Email?.Trim()))
            {
                validation = false;
            }
            if (string.IsNullOrEmpty(model.SecurityQuestion?.Trim()))
            {
                validation = false;
            }
            if (string.IsNullOrEmpty(model.SecurityAnswer?.Trim()))
            {
                validation = false;
            }
            if (string.IsNullOrEmpty(model.Password?.Trim()))
            {
                validation = false;
            }
            if (string.IsNullOrEmpty(model.VerPassword?.Trim()))
            {
                validation = false;
            }

            return validation;

        }
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Customer model)
        {

            if (!IsValidatiıon(model))
            {
                TempData["error"] += "Please fill the empty places. ";
                return View(model);
            }
            if (_customerService.CheckEmail(model.Email))
            {
                TempData["error"] += "This e-mail is already being used ";
                return View(model);
            }
            if (model.Password != model.VerPassword)
            {
                TempData["error"] += "Passwords do not match. ";
                return View(model);
            }

            model.RolId = _rolService.Get(x => x.Name == "Customer").First().Id;

            model.Password = MD5EncryptionCustom.MD5Encryption(model.Password);
            model.VerPassword = MD5EncryptionCustom.MD5Encryption(model.Password);
            _customerService.Add(model);

            return RedirectToAction("Index", "Login");
        }
    }
}

BBGymManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link href="~/Content/custom.css" rel="stylesheet" />
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BBGYM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Gym Membership", "GymMembership", "Category")</li>
                    <li>@Html.ActionLink("Personal Trainer", "PersonalTrainer", "Category")</li>
                    <li>@Html.ActionLink("Body Fat Calculator", "BodyFatCalculator", "Home")</li>
                </ul>
                <ul class="nav navbar-nav" style="float:right;">
                    @{
                        if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            var ticket = FormsAuthentication.Decrypt(HttpContext.Current.User.Identity.Name);
                            var userdata = ticket.UserData;
                            var roleName = userdata.Split(';')[1];
                            if (roleName == "Admin")
                            {
                                <li><a href="/Admin/Home/Index">Admin Panel</a></li>
                            }
                            <li>@Html.ActionLink("My Account", "MyAccount", "Home")</li>
                            <li><a href="#">@ticket.UserData.Split(';')[0]</a></li>
                            <li>@Html.ActionLink("LogOut", "Logout", "Login")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("SignIn", "Index", "Login")</li>
                            <li>@Html.ActionLink("SignUp", "Index", "Register")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
   
    <footer class="text-center" style=" height: 100px; bottom: 0; width: 100%;">
        <hr />
        <label style="margin-right:1.5rem;">@Html.ActionLink("Home", "Index", "Home")</label>
        <label style="margin-right:1.5rem;"> @Html.ActionLink("About", "About", "Home")</label>
        <label style="margin-right:1.5rem;">@Html.ActionLink("Contact", "Contact", "Home")</label>
        <label>&copy; @DateTime.Now.Year - My ASP.NET Application</label>
    </footer>
</body>
</html>